# Generated by Django 5.0.7 on 2024-07-23 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_keeping_unit', models.CharField(max_length=100, unique=True)),
                ('stock_quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternate_text', models.CharField(max_length=255)),
                ('url', models.ImageField(blank=True, help_text='Upload a Picture of Product', null=True, upload_to='')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.productline')),
            ],
        ),
    ]
