# Generated by Django 5.0.7 on 2024-07-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_productline_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productline',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductLine',
        ),
    ]
